# Generated by Django 4.2.14 on 2024-08-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time', 'name'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
