# Generated by Django 4.2.15 on 2024-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
