# Generated by Django 4.2.15 on 2024-09-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_slug_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
