# Generated by Django 4.2.15 on 2024-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_category_slug_alter_post_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='blog_catego_parent__604dc9_idx'),
        ),
    ]
